#!/bin/sh

if [ ! -z "$1" ]; then
  workspaces="-workspaces $1"
fi

exec acme-lsp -server '(\.c)|(\.h)|(\.cc)|(\.hh)|(\.cpp)|(\.hpp)$:clangd -log=error --background-index --limit-results=500 --completion-style=bundled' ${workspaces}